export const wallImages = [
  {
    title: "A REASON TO DIE",
    fileName: "/images/wall/items-sm/a-reason-to-die.png",
  },
  { title: "Brad", fileName: "/images/wall/items-sm/brad.png" },
  { title: "Dr Dao", fileName: "/images/wall/items-sm/dr-dao.png" },
  {
    title: "FRUCKS SUPREME LABS",
    fileName: "/images/wall/items-sm/frucks-supreme-labs.png",
  },
  { title: "Grebby", fileName: "/images/wall/items-sm/grebby.png" },
  { title: "Grug", fileName: "/images/wall/items-sm/grug.png" },
  { title: "Haqa", fileName: "/images/wall/items-sm/haqa.png" },
  {
    title: "Kevin Susanto",
    fileName: "/images/wall/items-sm/kevin-susanto.png",
  },
  { title: "Naqib", fileName: "/images/wall/items-sm/naqib.png" },
  { title: "Nayver", fileName: "/images/wall/items-sm/nayver.png" },
  { title: "ONEMINTNFT", fileName: "/images/wall/items-sm/onemintnft.png" },
  { title: "RememberMe", fileName: "/images/wall/items-sm/rememberme.png" },
  { title: "Shinraton", fileName: "/images/wall/items-sm/shinraton.png" },
  { title: "Somana", fileName: "/images/wall/items-sm/somana.png" },
  { title: "Waleswoosh", fileName: "/images/wall/items-sm/waleswoosh.png" },
  { title: "Wavez66", fileName: "/images/wall/items-sm/wavez66.png" },
  { title: "Adultarts", fileName: "/images/wall/items-sm/adultarts.png" },
  { title: "Asics", fileName: "/images/wall/items-sm/asics.png" },
  {
    title: "bitoordileone",
    fileName: "/images/wall/items-sm/bitoordileone.png",
  },
  { title: "BITSAVADOR", fileName: "/images/wall/items-sm/bitsavador.png" },
  { title: "BRANDONSALIM", fileName: "/images/wall/items-sm/brandonsalim.png" },
  { title: "Cisero Sarts", fileName: "/images/wall/items-sm/cisero-sarts.png" },
  { title: "CONSTQUARY", fileName: "/images/wall/items-sm/constquary.png" },
  { title: "Crypto Shira", fileName: "/images/wall/items-sm/crypto-shira.png" },
  {
    title: "CRYPTOVONDOOM",
    fileName: "/images/wall/items-sm/cryptovondoom.png",
  },
  { title: "Davekebo", fileName: "/images/wall/items-sm/davekebo.png" },
  { title: "Dominikyea", fileName: "/images/wall/items-sm/dominikyea.png" },
  { title: "Eliza", fileName: "/images/wall/items-sm/eliza.png" },
  {
    title: "Hollander Adam",
    fileName: "/images/wall/items-sm/hollander-adam.png",
  },
  { title: "jakegallen_", fileName: "/images/wall/items-sm/jakegallen_.png" },
  { title: "kingfrogbtc", fileName: "/images/wall/items-sm/kingfrogbtc.png" },
  { title: "Nacoleon", fileName: "/images/wall/items-sm/nacoleon.png" },
  { title: "Ola", fileName: "/images/wall/items-sm/ola.png" },
  { title: "OrdinalHO", fileName: "/images/wall/items-sm/ordinalho.png" },
  { title: "Ordllord", fileName: "/images/wall/items-sm/ordllord.png" },
  { title: "Otograf_jp", fileName: "/images/wall/items-sm/otograf_jp.png" },
  { title: "Paweldudko", fileName: "/images/wall/items-sm/paweldudko.png" },
  {
    title: "playmatejaylene",
    fileName: "/images/wall/items-sm/playmatejaylene.png",
  },
  { title: "PRANKSY", fileName: "/images/wall/items-sm/pranksy.png" },
  { title: "pryzmxbt", fileName: "/images/wall/items-sm/pryzmxbt.png" },
  { title: "Scrilla", fileName: "/images/wall/items-sm/scrilla.png" },
  { title: "Snooptoshi", fileName: "/images/wall/items-sm/snooptoshi.png" },
  { title: "1x3x", fileName: "/images/wall/items-sm/1x3x.png" },
  { title: "Anchovy", fileName: "/images/wall/items-sm/anchovy.png" },
  { title: "Biome77", fileName: "/images/wall/items-sm/biome77.png" },
  { title: "Boozy", fileName: "/images/wall/items-sm/boozy.png" },
  { title: "Cesar", fileName: "/images/wall/items-sm/cesar.png" },
  { title: "GMSATS", fileName: "/images/wall/items-sm/gmsats.png" },
  { title: "ItsaMrE", fileName: "/images/wall/items-sm/itsamre.png" },
  { title: "Joe", fileName: "/images/wall/items-sm/joe.png" },
  { title: "Kenny", fileName: "/images/wall/items-sm/kenny.png" },
  { title: "Knox", fileName: "/images/wall/items-sm/knox.png" },
  { title: "Lemonhaze", fileName: "/images/wall/items-sm/lemonhaze.png" },
  { title: "mac", fileName: "/images/wall/items-sm/mac.png" },
  {
    title: "MadisonOlivia",
    fileName: "/images/wall/items-sm/madisonolivia.png",
  },
  { title: "Miguel", fileName: "/images/wall/items-sm/miguel.png" },
  { title: "NEFU", fileName: "/images/wall/items-sm/nefu.png" },
  { title: "NFT Boi", fileName: "/images/wall/items-sm/nft-boi.png" },
  { title: "Nikola", fileName: "/images/wall/items-sm/nikola.png" },
  { title: "Ninjalerts", fileName: "/images/wall/items-sm/ninjalerts.png" },
  { title: "Nondualrandy", fileName: "/images/wall/items-sm/nondualrandy.png" },
  {
    title: "Profile Picture AI",
    fileName: "/images/wall/items-sm/profile-picture-ai.png",
  },
  { title: "Pyro", fileName: "/images/wall/items-sm/pyro.png" },
  { title: "Resaang", fileName: "/images/wall/items-sm/resaang.png" },
  { title: "Suganarium", fileName: "/images/wall/items-sm/suganarium.png" },
  { title: "T4T5", fileName: "/images/wall/items-sm/t4t5.png" },
  { title: "Tosyo", fileName: "/images/wall/items-sm/tosyo.png" },
  { title: "Troy Caylak", fileName: "/images/wall/items-sm/troy-caylak.png" },
  { title: "Blutoshi", fileName: "/images/wall/items-sm/blutoshi.png" },
  { title: "CBSPEARS", fileName: "/images/wall/items-sm/cbspears.png" },
  { title: "chartfu", fileName: "/images/wall/items-sm/chartfu.png" },
  { title: "D34thSt4lker", fileName: "/images/wall/items-sm/d34thst4lker.png" },
  { title: "Dazza", fileName: "/images/wall/items-sm/dazza.png" },
  { title: "Demon", fileName: "/images/wall/items-sm/demon.png" },
  { title: "Dorion", fileName: "/images/wall/items-sm/dorion.png" },
  { title: "Elena", fileName: "/images/wall/items-sm/elena.png" },
  { title: "Erin", fileName: "/images/wall/items-sm/erin.png" },
  { title: "fomojis", fileName: "/images/wall/items-sm/fomojis.png" },
  { title: "Franciss", fileName: "/images/wall/items-sm/franciss.png" },
  { title: "hammad", fileName: "/images/wall/items-sm/hammad.png" },
  { title: "Hunter Beast", fileName: "/images/wall/items-sm/hunter-beast.png" },
  { title: "Kermit", fileName: "/images/wall/items-sm/kermit.png" },
  {
    title: "King Bootoshi",
    fileName: "/images/wall/items-sm/king-bootoshi.png",
  },
  { title: "kuromi", fileName: "/images/wall/items-sm/kuromi.png" },
  { title: "Langerius", fileName: "/images/wall/items-sm/langerius.png" },
  { title: "lfg", fileName: "/images/wall/items-sm/lfg.png" },
  { title: "Marlonn", fileName: "/images/wall/items-sm/marlonn.png" },
  { title: "Matman 2", fileName: "/images/wall/items-sm/matman-2.png" },
  { title: "P4rma", fileName: "/images/wall/items-sm/p4rma.png" },
  { title: "Paradox", fileName: "/images/wall/items-sm/paradox.png" },
  { title: "Paris", fileName: "/images/wall/items-sm/paris.png" },
  { title: "RAF", fileName: "/images/wall/items-sm/raf.png" },
  { title: "Searchfi", fileName: "/images/wall/items-sm/searchfi.png" },
  { title: "Sheyi", fileName: "/images/wall/items-sm/sheyi.png" },
  { title: "Umeko", fileName: "/images/wall/items-sm/umeko.png" },
  { title: "Wades", fileName: "/images/wall/items-sm/wades.png" },
  { title: "XCPINATA", fileName: "/images/wall/items-sm/xcpinata.png" },
];
