export const wallImages = [
  {
    title: "Brrrbon",
    link: "https://twitter.com/Brrrbon_",
    fileName: "/images/wall/items/brrrbon.png",
    comment: "",
  },
  {
    title: "CBSpears",
    link: "https://twitter.com/cbspears",
    fileName: "/images/wall/items/cbspears.png",
    comment: "",
  },
  {
    title: "D34thSt4lker",
    link: "https://twitter.com/D34thSt4lker",
    fileName: "/images/wall/items/d34thSt4lker.png",
    comment: "Apes gonna ape",
  },
  {
    title: "Eliza",
    link: "https://twitter.com/redacted7777",
    fileName: "/images/wall/items/eliza.png",
    comment: "",
  },
  {
    title: "ETH Apple",
    link: "https://twitter.com/eth_apple",
    fileName: "/images/wall/items/404-apple.png",
    comment: "",
  },
  {
    title: "Ola",
    link: "https://twitter.com/thegreatola",
    fileName: "/images/wall/items/ola-elixir.png",
    comment: "",
  },
  {
    title: "Haqa",
    link: "https://twitter.com/TheHaQa",
    fileName: "/images/wall/items/haqa-cp.png",
    comment: "",
  },
  {
    title: "Finest Rares",
    link: "https://twitter.com/finestrares",
    fileName: "/images/wall/items/finestrarest.png",
    comment: "",
  },
  {
    title: "Nacoleon",
    link: "https://twitter.com/1nacoleon1",
    fileName: "/images/wall/items/nacoleon-btc.png",
    comment: "",
  },
  {
    title: "Nayver",
    link: "https://twitter.com/nayverfayver",
    fileName: "/images/wall/items/nayver-fayver.png",
    comment: "",
  },
  {
    title: "Nefu",
    link: "https://twitter.com/0xNefu",
    fileName: "/images/wall/items/nefu-fb.png",
    comment: "",
  },
  {
    title: "Blutoshi",
    link: "https://twitter.com/Blutoshi",
    fileName: "/images/wall/items/blu.png",
    comment: "",
  },
  {
    title: "Ordinally",
    link: "https://twitter.com/veryordinally",
    fileName: "/images/wall/items/ordinally.png",
    comment: "",
  },
  {
    title: "P4rma",
    link: "https://twitter.com/pfourma",
    fileName: "/images/wall/items/p4rma.png",
    comment: "",
  },
  {
    title: "Shinraton",
    link: "https://x.com/shin_raton",
    fileName: "/images/wall/items/shinraton.png",
    comment: "",
  },
  {
    title: "Umeko",
    link: "https://twitter.com/NFTsistersJAPAN",
    fileName: "/images/wall/items/umeko.png",
    comment: "Evolving with every heartbeat.🔥",
  },
  {
    title: "Tyler Whittle",
    link: "https://twitter.com/Dr_DAO_",
    fileName: "/images/wall/items/tyler-whittle.png",
    comment: "",
  },
  {
    title: "Xcpinata",
    link: "https://twitter.com/XCPinata",
    fileName: "/images/wall/items/xcpinata.png",
    comment: "",
  },
  {
    title: "Ssheyii",
    link: "https://twitter.com/ssheyii",
    fileName: "/images/wall/items/sheyi.png",
    comment: "",
  },
  {
    title: "Dazza",
    link: "https://twitter.com/dazza9x",
    fileName: "/images/wall/items/dazza9.png",
    comment: "",
  },
  // {
  //   title: "Langerius",
  //   link: "https://twitter.com/langeriuseth",
  //   fileName: "/images/wall/items/lemonhaze.png",
  //   comment: "",
  // },
  {
    title: "D0r10n",
    link: "https://twitter.com/d0r10n",
    fileName: "/images/wall/items/d0ri0n.png",
    comment: "",
  },
  {
    title: "0xGrug",
    link: "https://twitter.com/0xGrug",
    fileName: "/images/wall/items/grug.png",
    comment: "",
  },
  {
    title: "Wades",
    link: "https://twitter.com/Wades_ETH",
    fileName: "/images/wall/items/wades.png",
    comment: "",
  },
  {
    title: "Matman",
    link: "https://twitter.com/matman_xyz",
    fileName: "/images/wall/items/matman.png",
    comment: "Still grateful for the honorary, thanks",
  },
  {
    title: "Pacific Paradox",
    link: "https://twitter.com/PacificParadox",
    fileName: "/images/wall/items/pacific-paradox.png",
    comment: "",
  },
  {
    title: "HunterBeast",
    link: "https://twitter.com/cryptoquick",
    fileName: "/images/wall/items/hunter-beast.png",
    comment: "",
  },
  {
    title: "RAF",
    link: "https://twitter.com/RAF_BTC",
    fileName: "/images/wall/items/raf.png",
    comment: "",
  },
  {
    title: "OrdinalHO",
    link: "https://twitter.com/ordinalHO",
    fileName: "/images/wall/items/h-o.png",
    comment: "",
  },
  {
    title: "Barbra.sats",
    link: "https://twitter.com/thatwagmigirl",
    fileName: "/images/wall/items/barbra.png",
    comment: "",
  },
  {
    title: "Wavez66",
    link: "https://twitter.com/Wavez66",
    fileName: "/images/wall/items/wavez.png",
    comment: "",
  },
  {
    title: "Kuromi",
    link: "https://x.com/0xkuromi",
    fileName: "/images/wall/items/kuromi.png",
    comment: "",
  },
  {
    title: "Hammad",
    link: "https://twitter.com/Hammadbtc",
    fileName: "/images/wall/items/hammad.png",
    comment: "Wen",
  },
  {
    title: "Elenaa",
    link: "https://twitter.com/ElenaaETH",
    fileName: "/images/wall/items/elena.png",
    comment: "",
  },
  {
    title: "Erin",
    link: "https://twitter.com/realizingerin",
    fileName: "/images/wall/items/erin.png",
    comment: "",
  },
  {
    title: "Naqib",
    link: "https://twitter.com/Naqib_Noor",
    fileName: "/images/wall/items/naqib.png",
    comment: "",
  },
  {
    title: "Franc1s",
    link: "https://twitter.com/FullTiltFrancis",
    fileName: "/images/wall/items/franc1s.png",
    comment: "",
  },
  {
    title: "Chartfu",
    link: "https://twitter.com/ChartFuMonkey",
    fileName: "/images/wall/items/chartfu.png",
    comment: "",
  },
  {
    title: "King Bootoshi",
    link: "https://twitter.com/KingBootoshi",
    fileName: "/images/wall/items/king-bootoshi.png",
    comment: "",
  },
  {
    title: "Kermit",
    link: "https://twitter.com/crypto__kermit",
    fileName: "/images/wall/items/kermit.png",
    comment: "",
  },
  {
    title: "Demon",
    link: "https://twitter.com/ToTheDemon",
    fileName: "/images/wall/items/demon.png",
    comment: "",
  },
  {
    title: "Nikola Kingo",
    link: "https://twitter.com/Nikola_kingo",
    fileName: "/images/wall/items/nikola-kingo.png",
    comment: "",
  },
  {
    title: "Ceaser",
    link: "https://twitter.com/polkapheen",
    fileName: "/images/wall/items/nycryptopheen-eth.png",
    comment: "",
  },
  {
    title: "Eric Nelson",
    link: "https://twitter.com/EricNelson",
    fileName: "/images/wall/items/blessed.png",
    comment: "",
  },
  {
    title: "Marlon",
    link: "https://twitter.com/Marlonif",
    fileName: "/images/wall/items/marlonif.png",
    comment: "",
  },
  {
    title: "Miguel",
    link: "https://twitter.com/miguel_am88",
    fileName: "/images/wall/items/miguel.png",
    comment: "",
  },
  {
    title: "Pyro",
    link: "https://twitter.com/pyronft",
    fileName: "/images/wall/items/pyroshi.png",
    comment: "",
  },
  {
    title: "Wale",
    link: "https://twitter.com/waleswoosh",
    fileName: "/images/wall/items/wale-moca.png",
    comment: "",
  },
  {
    title: "Asics",
    link: "https://twitter.com/asicsbtc",
    fileName: "/images/wall/items/asics.png",
    comment: "",
  },
  {
    title: "Troy",
    link: "https://twitter.com/TroyCaylak",
    fileName: "/images/wall/items/troy.png",
    comment: "",
  },
  {
    title: "Knox",
    link: "https://twitter.com/Knox556",
    fileName: "/images/wall/items/knox.png",
    comment: "",
  },
  {
    title: "SugaR",
    link: "https://twitter.com/suganarium",
    fileName: "/images/wall/items/sugar.png",
    comment: "",
  },
  {
    title: "Nftboi",
    link: "https://twitter.com/nftboi_",
    fileName: "/images/wall/items/nftboi.png",
    comment: "",
  },
  {
    title: "Resaang",
    link: "https://twitter.com/resaang",
    fileName: "/images/wall/items/resaang.png",
    comment: "",
  },
  {
    title: "Kevsus",
    link: "https://x.com/KevinSusanto",
    fileName: "/images/wall/items/kevin-susanto.png",
    comment: "ifgggg",
  },
  {
    title: "Mac",
    link: "https://x.com/maccurated",
    fileName: "/images/wall/items/mac.png",
    comment: "",
  },
  {
    title: "Mr Anchovy",
    link: "https://x.com/Mr_Anchovy_",
    fileName: "/images/wall/items/mr-anchovy.png",
    comment: "Wen",
  },
  {
    title: "0x1x3x",
    link: "https://x.com/0x1x3x",
    fileName: "/images/wall/items/0x1x3x.png",
    comment: "",
  },
  {
    title: "Joe Rabbit",
    link: "https://x.com/JoeOrdinals",
    fileName: "/images/wall/items/joeordinals.png",
    comment: "",
  },
  {
    title: "Paris",
    link: "https://x.com/PARIS_sats",
    fileName: "/images/wall/items/paris.png",
    comment: "",
  },
  {
    title: "grebby",
    link: "https://x.com/vvvveth",
    fileName: "/images/wall/items/grebby.png",
    comment: "",
  },
  {
    title: "Tosyo",
    link: "https://x.com/bl0ckchainsavvy",
    fileName: "/images/wall/items/tosyo.png",
    comment: "",
  },
  {
    title: "Nondualrandy",
    link: "https://x.com/nondualrandy",
    fileName: "/images/wall/items/nondualrandy.png",
    comment: "",
  },
  {
    title: "ItsaMrE",
    link: "https://x.com/MrE_Btc",
    fileName: "/images/wall/items/itsamre.png",
    comment: "",
  },
  // {
  //   title: "Slingoor",
  //   link: "https://x.com/slingoor",
  //   fileName: "/images/wall/items/",
  // comment: "",
  // },
  {
    title: "Brad",
    link: "https://x.com/Brrrraad",
    fileName: "/images/wall/items/brrrraad.png",
    comment: "",
  },
  {
    title: "RememberMe",
    link: "#",
    fileName: "/images/wall/items/rememberme.png",
    comment: "",
  },
  {
    title: "Somana",
    link: "https://x.com/somanovich",
    fileName: "/images/wall/items/somana4.png",
    comment: "",
  },
  {
    title: "GMSats",
    link: "https://x.com/BitcoinNL",
    fileName: "/images/wall/items/gm-sats.png",
    comment: "",
  },
  {
    title: "Davekebo",
    link: "https://x.com/davekebo",
    fileName: "/images/wall/items/davekebo.png",
    comment: "",
  },
  {
    title: "LemonHaze",
    link: "https://x.com/Ordinals10K",
    fileName: "/images/wall/items/lemonhaze.png",
    comment: "",
  },
  {
    title: "B4Kenny",
    link: "https://x.com/b4kenny",
    fileName: "/images/wall/items/kenny.png",
    comment: "",
  },
  // {
  //   title: "OG General",
  //   link: "https://x.com/TheOG_General",
  //   fileName: "/images/wall/items/",
  // comment: "",
  // },
  {
    title: "The Hawk",
    link: "https://x.com/PackBagPoints",
    fileName: "/images/wall/items/the-hawk.png",
    comment: "",
  },
  // {
  //   title: "HausHope",
  //   link: "https://x.com/HausHoppe",
  //   fileName: "/images/wall/items/",
  // },
  {
    title: "T4T5",
    link: "https://x.com/t4t5",
    fileName: "/images/wall/items/t4t5.png",
    comment: "",
  },
  {
    title: "MoneyMike",
    link: "https://x.com/Moneymike_813",
    fileName: "/images/wall/items/moneymike.png",
    comment: "",
  },
  // {
  //   title: "Businessman",
  //   link: "https://x.com/businessmaneth",
  //   fileName: "/images/wall/items/",
  // comment: "",
  // },
  {
    title: "Jen Adultarts",
    link: "https://x.com/adultarts",
    fileName: "/images/wall/items/jen.png",
    comment: "",
  },
  {
    title: "CiseroSarts",
    link: "https://x.com/cicero_sats",
    fileName: "/images/wall/items/cicero.png",
    comment: "",
  },
  {
    title: "Playmatejaylene",
    link: "https://x.com/playmatejaylene",
    fileName: "/images/wall/items/jaylene.png",
    comment: "",
  },
  {
    title: "HollanderAdam",
    link: "https://x.com/HollanderAdam",
    fileName: "/images/wall/items/adam-hollander.png",
    comment: "",
  },
  {
    title: "Scrilla",
    link: "https://x.com/ScrillaVentura",
    fileName: "/images/wall/items/rare-scrilla.png",
    comment: "Ooof",
  },
  {
    title: "TommyTwoClubs",
    link: "https://x.com/TommyTwoClubs",
    fileName: "/images/wall/items/tommy-two-clubs.png",
  },
  {
    title: "PawelDuko",
    link: "https://x.com/PawelDudko",
    fileName: "/images/wall/items/pawel-dudko.png",
    comment: "",
  },
  {
    title: "OrdLord",
    link: "https://x.com/ordlordbtc",
    fileName: "/images/wall/items/ordlord.png",
    comment: "",
  },
  {
    title: "Snooptoshi",
    link: "https://x.com/uniqueNFT",
    fileName: "/images/wall/items/snooptoshi.png",
    comment: "",
  },
  {
    title: "NFTBawsa",
    link: "https://x.com/nftbawsa",
    fileName: "/images/wall/items/nft-bawsa.png",
  },
  {
    title: "Biome77",
    link: "https://x.com/biome77",
    fileName: "/images/wall/items/biome77.png",
    comment: "",
  },
  {
    title: "MadisonOlivia",
    link: "https://x.com/madisonoliviaa_",
    fileName: "/images/wall/items/madison-olivia.png",
    comment: "",
  },
  {
    title: "Dominikyea",
    link: "https://x.com/dominikyea",
    fileName: "/images/wall/items/dominikyea.png",
    comment: "",
  },
  {
    title: "ViolettaZironi",
    link: "https://x.com/ZironiVioletta",
    fileName: "/images/wall/items/violettazironi.png",
    comment: "",
  },
  {
    title: "0xBoozy Shamim Khan",
    link: "https://x.com/0xBoozy",
    fileName: "/images/wall/items/shamim-khan.png",
    comment: "",
  },
  {
    title: "CryptoShira",
    link: "https://x.com/CryptoShira",
    fileName: "/images/wall/items/shira-btc.png",
    comment: "",
  },
  {
    title: "Pryzmxbt",
    link: "https://x.com/pryzmxbt",
    fileName: "/images/wall/items/pryzm.png",
    comment: "",
  },
  {
    title: "InterfaceChiral",
    link: "https://x.com/interfaceChiral",
    fileName: "/images/wall/items/interfacechiral.png",
    comment: "",
  },
  {
    title: "Bitoordileone",
    link: "https://x.com/bitoordileone",
    fileName: "/images/wall/items/bito-ordileone.png",
    comment: "",
  },
  {
    title: "Otograf_jp",
    link: "https://x.com/otograf_jp",
    fileName: "/images/wall/items/oto.png",
    comment: "",
  },
  {
    title: "Punktoshi",
    link: "https://x.com/punktoshi1",
    fileName: "/images/wall/items/punktoshi.png",
    comment: "",
  },
  {
    title: "Jakegallen",
    link: "https://x.com/jakegallen_",
    fileName: "/images/wall/items/jakegallen.png",
    comment: "Oof",
  },
  {
    title: "Darklord.sats",
    link: "https://x.com/kingfrogbtc",
    fileName: "/images/wall/items/kingfrogbtc.png",
    comment: "",
  },
  {
    title: "Sam Supremelab Frucks",
    link: "https://x.com/supremelabs_io",
    fileName: "/images/wall/items/sam-supremelabs.png",
    comment: "",
  },
  {
    title: "Brandon Salim",
    link: "https://x.com/brandonsalim",
    fileName: "/images/wall/items/brandon-salim.png",
    comment: "It is not who is first, but who did it best",
  },
  {
    title: "Quary Sats",
    link: "https://x.com/const_quary",
    fileName: "/images/wall/items/quary-sats.png",
    comment: "",
  },
  {
    title: "VonDoom",
    link: "https://x.com/CryptoVonDoom",
    fileName: "/images/wall/items/vondoom.png",
    comment: "",
  },
  {
    title: "Mr BRC AReason2Die",
    link: "https://x.com/MrBRC0",
    fileName: "/images/wall/items/mr-brc.png",
    comment: "In deep thought over this one!",
  },
  {
    title: "1minute",
    link: "https://x.com/ONEMINNFT",
    fileName: "/images/wall/items/1minute.png",
    comment: "",
  },
  {
    title: "Pranksy",
    link: "https://x.com/pranksy",
    fileName: "/images/wall/items/pranksy.png",
    comment: "",
  },
  {
    title: "BitSavage",
    link: "https://x.com/bitsavador",
    fileName: "/images/wall/items/bitsavage.png",
    comment: "discord again",
  },
  {
    title: "Solemn",
    link: "https://x.com/strangersolemn",
    fileName: "/images/wall/items/stranger-solemn.png",
    comment: "",
  },
  {
    title: "MrE",
    link: "https://x.com/MrEdogtagnft",
    fileName: "/images/wall/items/mredogtagnft.png",
    comment: "",
  },
  {
    title: "Lordtuwu",
    link: "https://x.com/LordWorldPeace",
    fileName: "/images/wall/items/lord-world-peace.png",
    comment: "",
  },
  {
    title: "Loki89",
    link: "https://x.com/kewert420",
    fileName: "/images/wall/items/loki89.png",
    comment: "",
  },
  {
    title: "5P3C14L",
    link: "https://x.com/im5p3c14l",
    fileName: "/images/wall/items/5p3c14l.png",
    comment: "",
  },
  {
    title: "Vincent",
    link: "https://x.com/cryptolution101",
    fileName: "/images/wall/items/vincent-cryptolution.png",
    comment: "",
  },
  {
    title: "MasterChief",
    link: "https://x.com/MasterChiefNFTs",
    fileName: "/images/wall/items/masterchief.png",
    comment: "",
  },
  {
    title: "Bolt",
    link: "https://x.com/BoltXBT",
    fileName: "/images/wall/items/boltxbt.png",
    comment: "",
  },
  {
    title: "Error lunarsats",
    link: "https://x.com/lunarsats",
    fileName: "/images/wall/items/error-lunarsats.png",
    comment: "pushed",
  },
  {
    title: "Toony.btc",
    link: "https://x.com/0xtoony",
    fileName: "/images/wall/items/toony-btc.png",
    comment: "",
  },
  {
    title: "theartist.btc",
    link: "https://x.com/TheArtistBTC",
    fileName: "/images/wall/items/theartistbtc.png",
    comment:
      "I have been a nomad all my life, looking forward to being immortalised as one",
  },
  {
    title: "Royale",
    link: "https://x.com/royale_wit_whiz",
    fileName: "/images/wall/items/royale.png",
    comment: "I will share it soon! When is the mint? Did I get a gtd wl?	",
  },
  {
    title: "Sooltan",
    link: "https://x.com/sooltanbtc",
    fileName: "/images/wall/items/sooltan.png",
    comment: "",
  },
  {
    title: "Jexy",
    link: "https://x.com/jexybtc",
    fileName: "/images/wall/items/jexy.png",
    comment: "",
  },
  {
    title: "Erika Lee",
    link: "https://x.com/erikaleetv",
    fileName: "/images/wall/items/erikalee.png",
    comment: "",
  },
  {
    title: "Isabel Foxen Duke",
    link: "https://x.com/isabelfoxenduke",
    fileName: "/images/wall/items/isabel-foxen-duke.png",
    comment: "",
  },
  {
    title: "Erik",
    link: "https://x.com/BRC20Coins",
    fileName: "/images/wall/items/erik-brc20coins.png",
    comment: "",
  },
  {
    title: "Basel de' Medici",
    link: "https://x.com/bassel_amin",
    fileName: "/images/wall/items/bassel-amin.png",
    comment:
      "A - Airwa B - Breathin C - Circulation D - Deficit E  - Environment",
  },
  {
    title: "Himorasi",
    link: "https://x.com/himorazi",
    fileName: "/images/wall/items/himorazi.png",
    comment: "",
  },
  {
    title: "UFFIE",
    link: "https://x.com/NHKFF",
    fileName: "/images/wall/items/uffie.png",
    comment: "OOffie likes the website",
  },
  {
    title: "Monkey D Lucas",
    link: "https://x.com/LucasTuzo",
    fileName: "/images/wall/items/monkey-dlucas.png",
    comment: "",
  },
  {
    title: "Atitty",
    link: "https://x.com/Atitty_",
    fileName: "/images/wall/items/atitty.png",
    comment: "",
  },
  {
    title: "Danny Charts",
    link: "https://x.com/dannycharts",
    fileName: "/images/wall/items/danny-charts.png",
    comment: "",
  },
  {
    title: "KFZ",
    link: "https://x.com/KFZ_nfa",
    fileName: "/images/wall/items/kfz-nfa.png",
    comment: "",
  },
  {
    title: "GIRL in the VERSE",
    link: "https://x.com/girl_intheverse",
    fileName: "/images/wall/items/girl-in-the-verse.png",
    comment: "",
  },
  {
    title: "Yogi",
    link: "https://x.com/HouseofYogiX",
    fileName: "/images/wall/items/houseofyogix.png",
    comment: "",
  },
  {
    title: "Thehdr.btc",
    link: "https://x.com/thehdr002",
    fileName: "/images/wall/items/thehd-btc.png",
    comment: "",
  },
  {
    title: "Slick",
    link: "https://x.com/SlickBTC",
    fileName: "/images/wall/items/slick-btc.png",
    comment: "",
  },
  {
    title: "Clark",
    link: "https://x.com/Clark10x",
    fileName: "/images/wall/items/clark10x.png",
    comment: "",
  },
  {
    title: "Miko",
    link: "https://x.com/OrdinalMiko",
    fileName: "/images/wall/items/ordinalmiko.png",
    comment: "",
  },
  {
    title: "Jiurn",
    link: "https://x.com/Jiurn",
    fileName: "/images/wall/items/jiurn.png",
    comment: "",
  },
  {
    title: "pawellwitt",
    link: "https://x.com/pawellwitt",
    fileName: "/images/wall/items/pawell-witt.png",
    comment: "",
  },
  {
    title: "Shiro",
    link: "https://x.com/degenshiro",
    fileName: "/images/wall/items/degenshiro.png",
    comment: "",
  },
  {
    title: "Joona",
    link: "https://x.com/NFTJoona",
    fileName: "/images/wall/items/nftjoona.png",
    comment: "",
  },
  {
    title: "flame",
    link: "https://x.com/humanonfire",
    fileName: "/images/wall/items/flame-humanonfire.png",
    comment: "",
  },
  {
    title: "JPEGreg",
    link: "https://x.com/JPEGreg",
    fileName: "/images/wall/items/jpegreg.png",
    comment: "",
  },
  {
    title: "BitMonk",
    link: "https://x.com/BitMonk5060",
    fileName: "/images/wall/items/bitmonk5060.png",
    comment: "",
  },
  {
    title: "NFTFisherman",
    link: "https://x.com/nftfisherman",
    fileName: "/images/wall/items/nftfisherman.png",
    comment: "",
  },
  {
    title: "GIO",
    link: "https://x.com/GIOfortheWIN_",
    fileName: "/images/wall/items/gio.png",
    comment: "",
  },
  {
    title: "Genk Erserre",
    link: "https://x.com/erserre_",
    fileName: "/images/wall/items/genk-erserre.png",
    comment: "",
  },
  {
    title: "Kuyamark",
    link: "https://x.com/kuyamark",
    fileName: "/images/wall/items/kuyamark.png",
    comment: "",
  },
  {
    title: "Biggie",
    link: "https://x.com/Biggie_btc",
    fileName: "/images/wall/items/biggie-btc.png",
    comment: "",
  },
  {
    title: "Frogpoleon",
    link: "https://x.com/frogpoleon",
    fileName: "/images/wall/items/frogpoleon.png",
    comment: "",
  },
  {
    title: "WD40 W4nkpire",
    link: "https://x.com/W4nkpire",
    fileName: "/images/wall/items/w4nkpire.png",
    comment: "",
  },
  {
    title: "Kyltoshi",
    link: "https://x.com/kyltoshi",
    fileName: "/images/wall/items/kyltoshi.png",
    comment: "",
  },
  {
    title: "Raotosh1",
    link: "https://x.com/raotosh1",
    fileName: "/images/wall/items/raotosh1.png",
    comment: "",
  },
  {
    title: "CEOofthishousee",
    link: "https://x.com/ceoofthishousee",
    fileName: "/images/wall/items/ceoofthishousee.png",
    comment: "",
  },
  {
    title: "XTBegen",
    link: "https://x.com/xtbegen",
    fileName: "/images/wall/items/xtbegen.png",
    comment: "",
  },
  {
    title: "Yudag",
    link: "https://x.com/yudag",
    fileName: "/images/wall/items/yudag.png",
    comment: "",
  },
  {
    title: "Bubblegum Dee",
    link: "https://x.com/bubblegum_dee",
    fileName: "/images/wall/items/bubblegum-dee.png",
    comment: "",
  },
  {
    title: "Tclowdotsats",
    link: "https://x.com/tclowdotsats",
    fileName: "/images/wall/items/tclowdotsats.png",
    comment: "",
  },
  {
    title: "Tanner Cartier",
    link: "https://x.com/TannerCartier",
    fileName: "/images/wall/items/tanner-cartier.png",
    comment: "",
  },
  {
    title: "Krakker420",
    link: "https://x.com/Krakker420",
    fileName: "/images/wall/items/krakker420.png",
    comment: "",
  },
];
